name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Backend Docker Image
        run: docker build -t helix-backend ./backend

      - name: Build Flask AI Docker Image
        run: docker build -t helix-flask-ai ./flask-ai

      - name: Docker Compose Up
        run: docker-compose up -d --build